export enum BIBLE_BOOK_NAME {
  genesis = "genesis",
  exodo = "exodo",
  levitico = "levitico",
  numeros = "numeros",
  deuteronomio = "deuteronomio",
  josue = "josue",
  juizes = "juizes",
  rute = "rute",
  isamuel = "isamuel",
  iisamuel = "iisamuel",
  ireis = "ireis",
  iireis = "iireis",
  icronicas = "icronicas",
  iicronicas = "iicronicas",
  esdras = "esdras",
  neemias = "neemias",
  ester = "ester",
  jo = "jo",
  salmos = "salmos",
  proverbios = "proverbios",
  eclesiastes = "eclesiastes",
  cantares = "cantares",
  isaias = "isaias",
  jeremias = "jeremias",
  lamentacoes = "lamentacoes",
  ezequiel = "ezequiel",
  daniel = "daniel",
  oseias = "oseias",
  joel = "joel",
  amos = "amos",
  obadias = "obadias",
  jonas = "jonas",
  miqueias = "miqueias",
  naum = "naum",
  habacuque = "habacuque",
  sofonias = "sofonias",
  ageu = "ageu",
  zacarias = "zacarias",
  malaquias = "malaquias",
  mateus = "mateus",
  marcos = "marcos",
  lucas = "lucas",
  joao = "joao",
  atos = "atos",
  romanos = "romanos",
  icorintios = "icorintios",
  iicorintios = "iicorintios",
  galatas = "galatas",
  efesios = "efesios",
  filipenses = "filipenses",
  colossenses = "colossenses",
  itessalonisences = "itessalonisences",
  iitessalonisences = "iitessalonisences",
  itimoteo = "itimoteo",
  iitimoteo = "iitimoteo",
  tito = "tito",
  filemon = "filemon",
  hebreus = "hebreus",
  tiago = "tiago",
  ipedro = "ipedro",
  iipedro = "iipedro",
  ijoao = "ijoao",
  iijoao = "iijoao",
  iiijoao = "iiijoao",
  judas = "judas",
  apocalipse = "apocalipse",
}

export enum BIBLE_BOOK_ABBREVIATION {
  GN = "GN",
  EX = "EX",
  LV = "LV",
  NM = "NM",
  DT = "DT",
  JS = "JS",
  JZ = "JZ",
  RT = "RT",
  ISM = "ISM",
  IISM = "IISM",
  IRS = "IRS",
  IIRS = "IIRS",
  ICR = "ICR",
  IICR = "IICR",
  ED = "ED",
  NE = "NE",
  ES = "ES",
  JOH = "JOH",
  SL = "SL",
  PV = "PV",
  EC = "EC",
  CT = "CT",
  IS = "IS",
  JR = "JR",
  LM = "LM",
  EZ = "EZ",
  DN = "DN",
  OS = "OS",
  JL = "JL",
  AM = "AM",
  OB = "OB",
  JN = "JN",
  MQ = "MQ",
  NA = "NA",
  HC = "HC",
  SF = "SF",
  AG = "AG",
  ZC = "ZC",
  ML = "ML",
  MT = "MT",
  MC = "MC",
  LC = "LC",
  JO = "JO",
  AT = "AT",
  RM = "RM",
  ICO = "ICO",
  IICO = "IICO",
  GL = "GL",
  EF = "EF",
  FP = "FP",
  CL = "CL",
  ITS = "ITS",
  IITS = "IITS",
  ITM = "ITM",
  IITM = "IITM",
  TT = "TT",
  FM = "FM",
  HB = "HB",
  TG = "TG",
  IPE = "IPE",
  IIPE = "IIPE",
  IJO = "IJO",
  IIJO = "IIJO",
  IIIJO = "IIIJO",
  JD = "JD",
  AP = "AP",
}

const BibleAbbrvKVM = new Map([
  [BIBLE_BOOK_NAME.genesis, BIBLE_BOOK_ABBREVIATION.GN],
  [BIBLE_BOOK_NAME.exodo, BIBLE_BOOK_ABBREVIATION.EX],
  [BIBLE_BOOK_NAME.levitico, BIBLE_BOOK_ABBREVIATION.LV],
  [BIBLE_BOOK_NAME.numeros, BIBLE_BOOK_ABBREVIATION.NM],
  [BIBLE_BOOK_NAME.deuteronomio, BIBLE_BOOK_ABBREVIATION.DT],
  [BIBLE_BOOK_NAME.josue, BIBLE_BOOK_ABBREVIATION.JS],
  [BIBLE_BOOK_NAME.juizes, BIBLE_BOOK_ABBREVIATION.JZ],
  [BIBLE_BOOK_NAME.rute, BIBLE_BOOK_ABBREVIATION.RT],
  [BIBLE_BOOK_NAME.isamuel, BIBLE_BOOK_ABBREVIATION.ISM],
  [BIBLE_BOOK_NAME.iisamuel, BIBLE_BOOK_ABBREVIATION.IISM],
  [BIBLE_BOOK_NAME.ireis, BIBLE_BOOK_ABBREVIATION.IRS],
  [BIBLE_BOOK_NAME.iireis, BIBLE_BOOK_ABBREVIATION.IIRS],
  [BIBLE_BOOK_NAME.icronicas, BIBLE_BOOK_ABBREVIATION.ICR],
  [BIBLE_BOOK_NAME.iicronicas, BIBLE_BOOK_ABBREVIATION.IICR],
  [BIBLE_BOOK_NAME.esdras, BIBLE_BOOK_ABBREVIATION.ED],
  [BIBLE_BOOK_NAME.neemias, BIBLE_BOOK_ABBREVIATION.NE],
  [BIBLE_BOOK_NAME.ester, BIBLE_BOOK_ABBREVIATION.ES],
  [BIBLE_BOOK_NAME.jo, BIBLE_BOOK_ABBREVIATION.JOH],
  [BIBLE_BOOK_NAME.salmos, BIBLE_BOOK_ABBREVIATION.SL],
  [BIBLE_BOOK_NAME.proverbios, BIBLE_BOOK_ABBREVIATION.PV],
  [BIBLE_BOOK_NAME.eclesiastes, BIBLE_BOOK_ABBREVIATION.EC],
  [BIBLE_BOOK_NAME.cantares, BIBLE_BOOK_ABBREVIATION.CT],
  [BIBLE_BOOK_NAME.isaias, BIBLE_BOOK_ABBREVIATION.IS],
  [BIBLE_BOOK_NAME.jeremias, BIBLE_BOOK_ABBREVIATION.JR],
  [BIBLE_BOOK_NAME.lamentacoes, BIBLE_BOOK_ABBREVIATION.LM],
  [BIBLE_BOOK_NAME.ezequiel, BIBLE_BOOK_ABBREVIATION.EZ],
  [BIBLE_BOOK_NAME.daniel, BIBLE_BOOK_ABBREVIATION.DN],
  [BIBLE_BOOK_NAME.oseias, BIBLE_BOOK_ABBREVIATION.OS],
  [BIBLE_BOOK_NAME.joel, BIBLE_BOOK_ABBREVIATION.JL],
  [BIBLE_BOOK_NAME.amos, BIBLE_BOOK_ABBREVIATION.AM],
  [BIBLE_BOOK_NAME.obadias, BIBLE_BOOK_ABBREVIATION.OB],
  [BIBLE_BOOK_NAME.jonas, BIBLE_BOOK_ABBREVIATION.JN],
  [BIBLE_BOOK_NAME.miqueias, BIBLE_BOOK_ABBREVIATION.MQ],
  [BIBLE_BOOK_NAME.naum, BIBLE_BOOK_ABBREVIATION.NA],
  [BIBLE_BOOK_NAME.habacuque, BIBLE_BOOK_ABBREVIATION.HB],
  [BIBLE_BOOK_NAME.sofonias, BIBLE_BOOK_ABBREVIATION.SF],
  [BIBLE_BOOK_NAME.ageu, BIBLE_BOOK_ABBREVIATION.AG],
  [BIBLE_BOOK_NAME.zacarias, BIBLE_BOOK_ABBREVIATION.ZC],
  [BIBLE_BOOK_NAME.malaquias, BIBLE_BOOK_ABBREVIATION.ML],
  [BIBLE_BOOK_NAME.mateus, BIBLE_BOOK_ABBREVIATION.MT],
  [BIBLE_BOOK_NAME.marcos, BIBLE_BOOK_ABBREVIATION.MC],
  [BIBLE_BOOK_NAME.lucas, BIBLE_BOOK_ABBREVIATION.LC],
  [BIBLE_BOOK_NAME.joao, BIBLE_BOOK_ABBREVIATION.JO],
  [BIBLE_BOOK_NAME.atos, BIBLE_BOOK_ABBREVIATION.AT],
  [BIBLE_BOOK_NAME.romanos, BIBLE_BOOK_ABBREVIATION.RM],
  [BIBLE_BOOK_NAME.icorintios, BIBLE_BOOK_ABBREVIATION.ICO],
  [BIBLE_BOOK_NAME.iicorintios, BIBLE_BOOK_ABBREVIATION.IICO],
  [BIBLE_BOOK_NAME.galatas, BIBLE_BOOK_ABBREVIATION.GL],
  [BIBLE_BOOK_NAME.efesios, BIBLE_BOOK_ABBREVIATION.EF],
  [BIBLE_BOOK_NAME.filipenses, BIBLE_BOOK_ABBREVIATION.FP],
  [BIBLE_BOOK_NAME.colossenses, BIBLE_BOOK_ABBREVIATION.CL],
  [BIBLE_BOOK_NAME.itessalonisences, BIBLE_BOOK_ABBREVIATION.ITS],
  [BIBLE_BOOK_NAME.iitessalonisences, BIBLE_BOOK_ABBREVIATION.IITS],
  [BIBLE_BOOK_NAME.itimoteo, BIBLE_BOOK_ABBREVIATION.ITM],
  [BIBLE_BOOK_NAME.iitimoteo, BIBLE_BOOK_ABBREVIATION.IITM],
  [BIBLE_BOOK_NAME.tito, BIBLE_BOOK_ABBREVIATION.TT],
  [BIBLE_BOOK_NAME.filemon, BIBLE_BOOK_ABBREVIATION.FM],
  [BIBLE_BOOK_NAME.hebreus, BIBLE_BOOK_ABBREVIATION.HB],
  [BIBLE_BOOK_NAME.tiago, BIBLE_BOOK_ABBREVIATION.TG],
  [BIBLE_BOOK_NAME.ipedro, BIBLE_BOOK_ABBREVIATION.IPE],
  [BIBLE_BOOK_NAME.iipedro, BIBLE_BOOK_ABBREVIATION.IIPE],
  [BIBLE_BOOK_NAME.ijoao, BIBLE_BOOK_ABBREVIATION.IJO],
  [BIBLE_BOOK_NAME.iijoao, BIBLE_BOOK_ABBREVIATION.IIJO],
  [BIBLE_BOOK_NAME.iiijoao, BIBLE_BOOK_ABBREVIATION.IIIJO],
  [BIBLE_BOOK_NAME.judas, BIBLE_BOOK_ABBREVIATION.JD],
  [BIBLE_BOOK_NAME.apocalipse, BIBLE_BOOK_ABBREVIATION.AP],
]);
export { BibleAbbrvKVM };

export class JsonBook {
  abbrev: string;
  chapters: [][];
  name: string;
}

export class DBVerse {
  name: string;
  abbrev: string;
  chapterId: number;
  verseId: number;
  verseDescription: string;
}

export class DBRequestBody {
  abbrev: string;
  chapterId: number;
  verseIdStart: number;
  verseIdEnd?: number;
}

export class BibleRequestBody {
  book: string;
  chapterId: number;
  verseIdStart: number;
  verseIdEnd?: number;
}

export class BibleReturn {
  data: DBVerse[];
}
